### ISSUE TITLE
remove .ddev directory

### ISSUE THREAD

**Issue by gilzow** [platformsh-templates/nextjs-drupal#7]
the configuration in .ddev/config.yaml is not connected to the configuration in .platform.app.yaml and therefore can drift and fall out-of-sync. Suggest removing .ddev directory and instead point users to the ddev+platformsh addon instructions.

**Comment by rfay** [comment]
Let's please get rid of the .ddev directory! And the one that's a subdirectory?

**Comment by rfay** [comment]
Removal in 
* https://github.com/platformsh-templates/nextjs-drupal/pull/11

**Comment by rfay** [comment]
> instead point users to the ddev-platformsh addon instructions

Not sure they should need the ddev-platformsh add-on but should try this out.

I think this is a multi-app recipe that DDEV probably doesn't know how to deal with though?
